name: CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, CI/CD!"

      - name: Another greeting
        run: echo "Hello, CI/CD again!"
      
      

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, CI/CD!"

      #- name: Simulate an error
        #run: echo "About to fail" ; exit 1

      - name: Another greeting
        run: echo "Hello, CI/CD again!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, CI/CD!"

      - name: Another greeting
        run: echo "Hello, CI/CD again!"